sharepoint_client_id: ${SHAREPOINT_CLIENT_ID}
sharepoint_tenant_id: ${SHAREPOINT_TENANT_ID}
sharepoint_client_secret: ${SHAREPOINT_CLIENT_SECRET}

embedding_model:
  azure_openai:
    key: ${METAPHOR_AZURE_OPENAI_KEY}
    endpoint: ${METAPHOR_AZURE_OPENAI_ENDPOINT}

include_text: true