confluence_base_URL: https://metaphor-test.atlassian.net/wiki
confluence_cloud: true
select_method: "label"

confluence_username: ${CONFLUENCE_USERNAME}
confluence_token: ${CONFLUENCE_PASSWORD}

space_key: ${SPACE_KEY}

embedding_model:
  azure_openai:
    key: ${METAPHOR_AZURE_OPENAI_KEY}
    endpoint: ${METAPHOR_AZURE_OPENAI_ENDPOINT}
    
include_text: true