sharepoint_client_id: ${SHAREPOINT_CLIENT_ID}
sharepoint_tenant_id: ${SHAREPOINT_TENANT_ID}
sharepoint_client_secret: ${SHAREPOINT_CLIENT_SECRET}

embed_source: azure-openai
embed_model_config:
    azure_openAI_key: ${METAPHOR_AZURE_OPENAI_KEY}
    azure_openAI_endpoint: ${METAPHOR_AZURE_OPENAI_ENDPOINT}

include_text: true