name: cd

on:
  push:
    branches: [main]

  schedule:
  # Runs daily at 6am
    - cron: 0 6 * * *

jobs:
  cd:
    strategy:
      matrix:
        env:
          - stage
          - qa
          - demo
          - sandbox
    uses: MetaphorData/connectors-action/.github/workflows/shared.yml@main
    with:
        env: ${{ matrix.env }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
