name: manual

on:
  workflow_dispatch:
      inputs:
          env:
              description: Environment to publish to (e.g. dev-marslan, stage, etc.)
              required: true

jobs:
  manual:
    uses: ./.github/workflows/shared.yml
    with:
        env: ${{ inputs.env }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
