name: monday_manual

on:
  workflow_dispatch:
      inputs:
          target_board:
              description: Monday.com board ID to extract. Must be in the metaphor-ensemble workspace.
              required: true
          env:
              description: Environment to publish to (e.g. dev-marslan, stage, etc.)
              required: true

      secrets:
        AWS_ACCESS_KEY_ID:
          description: AWS access key ID for deployment
          required: true

        AWS_SECRET_ACCESS_KEY:
          description: AWS secret access key for deployment
          required: true

        METAPHOR_AZURE_OPENAI_KEY:
          description: Azure OpenAI services key
          required: true

        MONDAY_API_KEY:
          description: Monday.com API key
          required: true
      
jobs:
  monday-crawl:
    name: Monday.com Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create config file with boards
        run: |
          echo "" >> .github/workflows/configs/config_monday.yml
          echo "boards: [${{ inputs.target_board }}]" >> .github/workflows/configs/config_monday.yml

      - uses: MetaphorData/connectors-action@v0.13
        env:
            TARGET_BOARD: ${{ inputs.target_board }}
            MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
            METAPHOR_AZURE_OPENAI_KEY: ${{ secrets.METAPHOR_AZURE_OPENAI_KEY }}
            METAPHOR_AZURE_OPENAI_ENDPOINT: ${{ vars.METAPHOR_AZURE_OPENAI_ENDPOINT }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-west-2
        with:
            type: monday
            config: .github/workflows/configs/config_monday.yml
            s3-path: s3://metaphor-mce-${{ inputs.env }}/monday
