name: notion_manual

on:
  workflow_dispatch:
      inputs:
          env:
              description: Environment to publish to (e.g. dev-marslan, stage, etc.)
              required: true

      secrets:
        AWS_ACCESS_KEY_ID:
          description: AWS access key ID for deployment
          required: true

        AWS_SECRET_ACCESS_KEY:
          description: AWS secret access key for deployment
          required: true

        METAPHOR_AZURE_OPENAI_KEY:
          description: Azure OpenAI services key
          required: true

        NOTION_API_TOKEN:
          description: Notion integration token
          required: true
      
jobs:
  notion-crawl:
    name: Notion Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: MetaphorData/connectors-action@v0.13
        env:
            OPENAI_API_KEY: "thisisadummyapikey123456789"
            METAPHOR_AZURE_OPENAI_KEY: ${{ secrets.METAPHOR_AZURE_OPENAI_KEY }}
            NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-west-2
        with:
            type: notion
            config: .github/workflows/configs/config_notion.yml
            s3-path: s3://metaphor-mce-${{ inputs.env }}/notion
