name: scheduled_connectors

on:
  schedule:
  # Runs daily at 11PM PST
    - cron: 0 6 * * *

jobs:
  cd:
    strategy:
      matrix:
        env:
          - stage
          - qa
          - demo
    uses: ./.github/workflows/external_document_connectors.yml
    with:
        env: ${{ matrix.env }}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
