name: scheduled_connectors_sandbox

on:
  schedule:
  # Runs daily at 11PM PST
    - cron: 0 6 * * *

jobs:
  run-connectors:
    uses: ./.github/workflows/external_document_connectors.yml
    with:
        env: sandbox
    secrets: inherit
