name: sharepoint_manual

on:
  schedule:
    - cron: "0 6 * * *"  # 11PM PST daily
  workflow_dispatch:
      inputs:
          env:
              description: Environment to publish to (e.g. dev-marslan, stage, etc.)
              required: true

      secrets:
        AWS_ACCESS_KEY_ID:
          description: AWS access key ID for deployment
          required: true

        AWS_SECRET_ACCESS_KEY:
          description: AWS secret access key for deployment
          required: true

        METAPHOR_AZURE_OPENAI_KEY:
          description: Azure OpenAI services key
          required: true

        SHAREPOINT_CLIENT_SECRET:
          description: Azure AD App client secret
          required: true
      
jobs:
  sharepoint-crawl:
    name: Sharepoint Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up defaults for scheduled run
        if: github.event_name == 'schedule'
        run: |
          echo "OUTPUT_ENV=stage" >> $GITHUB_ENV

      - name: Set up variables from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "OUTPUT_ENV=${{ inputs.env }}" >> $GITHUB_ENV

      - uses: MetaphorData/connectors-action@v0.14
        env:
            SHAREPOINT_CLIENT_ID: ${{ vars.CLIENT_ID }}
            SHAREPOINT_TENANT_ID: ${{ vars.TENANT_ID }}
            SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
            METAPHOR_AZURE_OPENAI_KEY: ${{ secrets.METAPHOR_AZURE_OPENAI_KEY }}
            METAPHOR_AZURE_OPENAI_ENDPOINT: ${{ vars.METAPHOR_AZURE_OPENAI_ENDPOINT }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-west-2
        with:
            type: sharepoint
            config: .github/workflows/configs/config_sharepoint.yml
            s3-path: s3://metaphor-mce-${{ env.OUTPUT_ENV }}/sharepoint
